{
 "title": "Integration Service NGINX Log Updated",
 "time": { "from": "2023-03-15T06:02:55.397Z", "to": "2023-03-15T06:12:55.397Z" },
 "panels": [
  {
   "title": "ClearingGross/Create",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Amount calls",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/ClearingGross/Create\" [24h]))"
      }
     ]
    },
    {
     "title": "Minimum Response Time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(resp_time) (max_over_time({filename=\"iapi4.bakai.local-access.log.1\"} |= \"/OnlineBank.IntegrationService/api/ClearingGross/Create\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "api/Customers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Amount Calls",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Customers/\" [24h]))"
      }
     ]
    },
    {
     "title": "Minimum Response Time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(resp_time) (max_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Customers/\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [48h]))"
      }
     ]
    },
    {
     "title": "Avarage Response Time",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(resp_time) (avg_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Customers/\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [48h]))"
      }
     ]
    },
    {
     "title": "Maximum response time",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 18, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min  by(resp_time) (min_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Customers/\"  | regexp \"(?P<resp_time>resp_time:[-0-9-.]+)\" | unwrap resp_time [24h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions/GetState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Amount calls",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/GetState\" [24h]))"
      }
     ]
    },
    {
     "title": "Minimum Response Time",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(resp_time) (max_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/GetState\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]))"
      }
     ]
    },
    {
     "title": "Avarage time Response",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(resp_time) (avg_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/GetState\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [48h]))"
      }
     ]
    },
    {
     "title": "Maximum Response Time",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min  by(resp_time) (min_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/GetState\"  | regexp \"(?P<resp_time>resp_time:[-0-9-.]+)\" | unwrap resp_time [24h]))"
      }
     ]
    },
    {
     "title": "P95",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile_over_time(0.95,{job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/GetState\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]) "
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction/Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number calls",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\" [24h]))"
      }
     ]
    },
    {
     "title": "Minimum Response time by max",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 3, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (resp_time) (max_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [48h]))"
      }
     ]
    },
    {
     "title": "Avarage Time Response",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 7, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(resp_time) (avg_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]))"
      }
     ]
    },
    {
     "title": "Maximum Time Response",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 11, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by (resp_time) (min_over_time({job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]))"
      }
     ]
    },
    {
     "title": "P95",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile_over_time(0.20,{job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]) "
      }
     ]
    },
    {
     "title": "P99",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "quantile_over_time(0.99,{job=\"integration_service_access_log\"} |= \"/OnlineBank.IntegrationService/api/Transactions/Operation\"  | regexp \"(?P<resp_time>resp_time:-([0-9]+\\\\.[0-9]+)-)\"  | unwrap resp_time [24h]) "
      }
     ]
    }
   ]
  }
 ]
}